json_data = {
  "transportCompany": 48112,
  "crane": null,
  "trailer": null,
  "computer": null,
  "numberOfAxles": 2,
  "users": [
    "1059625"
  ],
  "forestCompanies": [
    "1",
    "2"
  ],
  "deliveryOrigins": [],
  "vehicleType": "TIMBER_TRUCK",
  "resourceIdentifier": "LAA",
  "name": "TestiTesti",
  "active": true,
  "canCarryRoundWood": "true",
  "canCarryByProduct": "true",
  "canCarryProcessChips": "true",
  "canCarryForestEnergy": "true",
  "canLoadRoundWood": "",
  "canLoadByProduct": "",
  "canLoadProcessChips": "",
  "canLoadForestEnergy": "",
  "canCarryRoundWoodInForest": "true",
  "roundTripCapable": "true",
  "deploymentDate": "2016-01-29T00:00:00+02:00",
  "seasonal": true,
  "seasonBeginDate": "2016-01-29T00:00:00+02:00",
  "seasonEndDate": "2016-01-31T00:00:00+02:00",
  "make": "JOU",
  "model": "",
  "shift": "2",
  "cargoVolume1": null,
  "cargoVolume1Unit": "m3",
  "cargoVolume2": null,
  "cargoVolume2Unit": "m3",
  "cargoVolume3": null,
  "cargoVolume3Unit": "m3",
  "carryingCapacity": null,
  "sidePlateType": "SOLID_SIDE_PLATES",
  "tractorTrailerType": null,
  "unloadMethod": null,
  "mobility": null,
  "feedType": null,
  "hourlyOutputIM3": null,
  "hourlyOutputM3": null,
  "hourlyOutputMWh": null,
  "homeLocation": null,
  "chippersAndCrushers": null,
  "emptyWeight": 9000,
  "phoneNumber": null
}